version: "3"

volumes:
  data: {}

services:
  streamlit:
    build:
      context: .
      target: prod
    image: refida:0.2.0
    volumes:
      - data:/app/data
    ports:
      - "8201:8000"
    restart: unless-stopped
